apiVersion: v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    app: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        imagePullPolicy: Always
        image: tonytronics5/simple-express-reverse-proxy
        ports:
        - containerPort: 8080
        
